### ISSUE TITLE
Consider using <app-route> and <app-location>

### ISSUE THREAD

**Issue by oneezy** [them-es/themes-starter-spa#1]
Polymer team created the `<app-route>` [(link)](https://www.webcomponents.org/element/PolymerElements/app-route) custom element.

Do you have any plans to use this instead of `page.js` ?

**Comment by them-es** [comment]
Thanks for getting in touch. The current version v1.1 which has been released in October 2016 already makes use of the `<app-route>` element. `page.js` is not supported anymore.

You can download a new Starter theme here [https://them.es/starter-spa](https://them.es/starter-spa)

**Comment by oneezy** [comment]
ahhh, cool! thanks for the clarification :D
