### ISSUE TITLE
Missing Files: manifest.json, polymer.json, server-worker.js, sw-precache-config.js ?

### ISSUE THREAD

**Issue by oneezy** [them-es/themes-starter-spa#2]
When comparing Polymer Starter Kit w/ the Themes Starter Spa, I've noticed a few differences in the file structure along with a few missing files. 

Is there a specific reason you didn't include the `polymer.json`, `manifest.json`, `service-worker.js` or `sw-precache-config.js` ? 

I went ahead and highlighted all the differences in the comparison below

---

![image](https://cloud.githubusercontent.com/assets/7369575/23798911/34042c28-056c-11e7-8309-c9cd5e805e6c.png)

**Comment by them-es** [comment]
`polymer.json` is required for the [Polymer CLI](https://www.polymer-project.org/2.0/docs/tools/polymer-cli)

`service-worker.js` and `sw-precache-config.js` are required for e.g. push-notifications/offline-use.

The WordPress Starter Theme does not use any of these features right now as it should be seen as a basic starting point for Theme developers. Feel free to add additional features to your Theme sources if required.

**Comment by oneezy** [comment]
thanks for your response! 

Your theme looks to be more inline w/ the old Polymer Starter Kit [(version 1.0)](https://github.com/PolymerElements/polymer-starter-kit/tree/v1.0.0/app). 

I think it could work w/ some editing, but I ended up using [this project](https://github.com/trofrigo/polymer-theme) because it was more up to date w/ the current Polymer Starter Kit [(version 2.0)](https://github.com/PolymerElements/polymer-starter-kit)

---

You guys should maybe combine forces 😀

**Comment by them-es** [comment]
Thanks for your feedback. PSK v2 definitely has some features and code snippets which make sense to incorporate into our WordPress theme.

Stay tuned 😀

**Comment by oneezy** [comment]
Excellent! :smile::smile::smile::smile::smile::smile:
