### ISSUE TITLE
Iron page default value wrong

### ISSUE THREAD

**Issue by codesenpaii** [them-es/themes-starter-spa#3]
If you open another page it always go to index. I think it has something to do with the iron page value. 
For example open the feature page: https://them.es/starter-spa/features/, but it will load the index page not the feature page. I'm using chrome 62.

In my case, it will be fixed by removing `.` (dot) from the pattern attribute in the app-route component.

Before : 
```
<app-route route="{{route}}" pattern="./:page"
```

After: 
```
<app-route route="{{route}}" pattern="/:page"
```

**Comment by them-es** [comment]
Thanks for reporting the issue. The pages did not load on Multisite enabled sites using subdirectories. It has been fixed now:

https://github.com/them-es/themes-starter-spa/blob/51802d7fbf36b4a371a5c836039c44ec0e246c5d/elements/starter-app.php#L133

Let me know if that works for you.
