### ISSUE TITLE
Non-multisite error using get_blog_details function

### ISSUE THREAD

**Issue by NickdeK** [them-es/themes-starter-spa#4]
Logs show a error "Call to undefined function get_blog_details()". The error is caused by this change: c215a6cf73ee0447b241cf46b9baec430cb4e9ff When this change is reverted the problem goes away.

**Comment by them-es** [comment]
Thank you for reporting this issue @NickdeK. It has been resolved in the latest version: https://github.com/them-es/themes-starter-spa/commit/230f3f19d576771f9186c54bfa085776bc11cce0
